---

engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
    exclude_fingerprints:
      - efbc648172f3fa9a34e3da2937ee2fb8
      - ca067b6f9d7b2ff4c1412fef42db78b6
  fixme:
    enabled: true
  eslint:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/TrailingBlankLines:
        enabled: false
      Rubocop/Style/GlobalVars:
        enabled: true
        AllowedVariables: [$CLIENT_ID, $CLIENT_SECRET]
    exclude_fingerprints:
      - cbee5412ef89b2509bfc04c790d1f50f
      - 1e76411a6b5ac5f855d9d7aa437d82ad
      - abbb6927aa366917180792edd397d0a5
  scss-lint:
    enabled: true

ratings:
  paths:
    - "**.rb"
    - "**.js"
    - "**.css"
    - "**.sass"
