---

engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
  fixme:
    enabled: true
  eslint:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/TrailingBlankLines:
        enabled: false
  scss-lint:
    enabled: true

ratings:
  paths:
    - "**.rb"
    - "**.js"
    - "**.css"
    - "**.sass"
