---

engines:
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
    exclude_fingerprints:
      - efbc648172f3fa9a34e3da2937ee2fb8
      - ca067b6f9d7b2ff4c1412fef42db78b6
  fixme:
    enabled: true
  eslint:
    enabled: true
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/TrailingBlankLines:
        enabled: false
      Rubocop/Style/GlobalVars:
        enabled: true
        AllowedVariables: [$CLIENT_ID, $CLIENT_SECRET]
    exclude_fingerprints:
      - cbee5412ef89b2509bfc04c790d1f50f
      - 1e76411a6b5ac5f855d9d7aa437d82ad
      - abbb6927aa366917180792edd397d0a5
      - dfd42f4ec9538db9b23a1c559f9b2460
      - 7c95a732db38d968252218dc25196c81
      - 3cfbf36e361979a17b130e445f86a81a
      - e957c77eace17b2a7b5b5cd680cc268e
      - e034839a5df93ca344a72ac8ac83b0d9
      - c866fedf1f24f51db531d05f1daa6244
  scss-lint:
    enabled: true

ratings:
  paths:
    - "**.rb"
    - "**.js"
    - "**.css"
    - "**.sass"
