#%RAML 1.0
---

title: oxidized-web API
baseUri: http://oxidized.example.com
version: v1

types:
  Version:
    schema: !include schemas/version.json
    example: !include samples/version.json

resourceTypes:
  Collection:
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>[]
  Member:
    get:
      responses:
        200:
          body:
            application/json:
              type: <<item>>

/versions:
  /{group}:
    /{hostname}:
      type:
        Collection:
          item: Version
      get:
        queryParameters:
          format:
            displayName: format
            type: string
            description: The format of the data for the API to return
            example: json
            required: false
            enum: ['json']
